baseURL = "https://vigotech.github.io"
languageCode = "gl-es"
title = "Vigo Tech Alliance"
publishDir = "docs"
theme = "hugoscroll"

[Params]
  github = "VigoTech"
  twitter = "vigotechallianc"
  email = "alliance@vigotech.org"
  description = "Os grupos de tecnoloxía de Vigo facemos piña para promover a tecnoloxía na cidade"
  cover = "/images/bg.jpg"
  logo = "/images/logo_white.jpg"
